---
title: "Manula for functions for connect to the API of Swedish Parliment website"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(rvest)
library(stringr)
library(tibble)
library(dplyr)
library(readr)
library(usethis)

parliments_source <-  "https://www.riksdagen.se/en/members-and-parties/members/"


```
# Get the names of all parties

```{r}
get_parties <- function () {
  return (list('The Social Democratic Party'='socdem',
               'The Sweden Democrats'='swedem',
               'The Moderate Party'='mod',
               'The Left Party'='lft',
               'The Centre Party'='cen',
               'The Christian Democrats'='chrdem',
               'The Green Party'='grn',
               'The Liberal Party'='lib'))
}
```

# Grab member information by their belonging parties
##  Get Members' detail URLs by their parties
```{r}
get_name_return_detail_url_by_party <- function (html,parti) {
  member_detail_urls <- list()
  member_detail_nodes <-html %>%
    html_nodes("#__next")%>%
    html_nodes("div.sc-e76b6126-0.iAtpHa")%>%
    html_nodes("div:nth-child(1)")%>%
    html_nodes("div.sc-fc94b50d-1.icalgq") %>%
    html_nodes('a')
  member_detail_urls <- member_detail_nodes %>%  html_attr(name = "href")
  return (list(member_detail_urls))
}
# use the function to get the urls for members in left party
html <- read_html("https://www.riksdagen.se/en/members-and-parties/members/")
get_name_return_detail_url_by_party(html,'lft')
```

## Extract detailed information of members based on their urls
```{r}
get_member_detail_info <- function(detail_url, party_member_info_df) {
  for (url in detail_url) {
    single_member_info <- list()
    detail_html <- read_html(url)
    info_nodes <- detail_html %>%
      html_nodes("#content") %>%
      html_nodes("div.sc-e76b6126-1.koghww")
    name <- info_nodes %>% html_nodes("h1") %>% html_text(trim = TRUE)
    single_member_info$Name <- c(name)
    info_names <- info_nodes %>% html_nodes("dt") %>% html_text(trim = TRUE)
    infos <- info_nodes %>% html_nodes("dd") %>% html_text(trim = TRUE)

    for (i in 1:length(info_names)) {
      att_name <- gsub("[^a-zA-Z]", "", info_names[[i]])
      info_value <- infos[[i]]

      if (!att_name %in% colnames(party_member_info_df)) {
        party_member_info_df[[att_name]] <- rep(NA, nrow(party_member_info_df))
      }

      single_member_info[[att_name]] <- c(info_value)

      if (att_name == 'Birthyear' && !is.null(info_value)) {
        age <- as.numeric(format(Sys.Date(), "%Y")) - as.numeric(info_value)
        single_member_info$Age <- c(age)
      }
    }

    single_member_df <- data.frame(single_member_info)
    party_member_info_df <- bind_rows(party_member_info_df, single_member_df)
  }

  return(party_member_info_df)
}
# apply the function for the first url of the results for left party 
detail_urls <- 'https://www.riksdagen.se/en/members-and-parties/member/fredrik-ahlstedt_8403346f-0f0c-4d48-bbd0-f6b43b368873/'
member_info_df <- tibble(
    Name = character(),
    Party = character(),
    Constituency = character(),
    Birthyear = character(),
    Address = character(),
    Email = character(),
    Telephone = character(),
    Title = character(),
    Age = numeric()
  )
get_member_detail_info(detail_urls, member_info_df)
```

## Define the path and name to register members basic information
```{r}
register_data <- function(member_basic_info, party) {
  file_name <- "member_basic_info.csv"
  file_path <- paste("data-raw/", file_name, sep="")
  write_csv(member_basic_info, file_path)
  usethis::use_data(member_basic_info, overwrite = TRUE)
}
```



# Get each member's names and other information through their urls
```{r}
catch_member_info_by_party <- function(parliments_source){
  member_info_df <- tibble(
    Name = character(),
    Party = character(),
    Constituency = character(),
    Birthyear = character(),
    Address = character(),
    Email = character(),
    Telephone = character(),
    Title = character(),
    Age = numeric()
  )
  parties <- unlist(get_parties())
  for (parti in parties) {
    cat(sprintf("start to catch name of member of %s \n" , parti))
    party_url <- paste(parliments_source,'?parti=' , parti, sep="")
    html <- read_html(party_url)
    member_detail_urls <- get_name_return_detail_url_by_party(html,parti)
    party_member_info_df <- get_member_detail_info(member_detail_urls[[1]],member_info_df)
    member_info_df <- bind_rows(member_info_df,party_member_info_df)
    member_info_df <- member_info_df %>% distinct(Name, .keep_all = TRUE)
    cat(sprintf("have record number of member:%d \n", nrow(member_info_df)))
  }
  register_data(member_info_df,parti)
}

```




